version: "3.9"

services:
  sqlai-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlai-server
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
    command: uvicorn src.main:app --host 0.0.0.0
    restart: unless-stopped
    network_mode: bridge
